### ISSUE TITLE
PERMISSIONS

### ISSUE THREAD

**Issue by giantfurkii** [NickHippen/ColoredAnvils#1]
![image](https://user-images.githubusercontent.com/78488589/134759482-0d2ae310-7ad8-4181-9cc7-7a0cee346729.png)
I don't want to give my players the "&k" format, how can I set it up ?

**Comment by NickHippen** [comment]
You'll have to give your players every permission, _but &k_, rather than using wildcards. In other words:

coloredanvils.color.hex
coloredanvils.color.l
coloredanvils.color.m
coloredanvils.color.n
coloredanvils.color.o
coloredanvils.color.r
